# Generated by Django 5.1.3 on 2024-11-12 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BusinessBorrower",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "loan_number",
                    models.CharField(default=12345, max_length=20, unique=True),
                ),
                ("name", models.CharField(default="Unknown Borrower", max_length=255)),
                ("city", models.CharField(default="Unknown City", max_length=100)),
                ("state", models.CharField(default="CA", max_length=2)),
                ("zip_code", models.CharField(default="00000", max_length=10)),
                ("bank", models.CharField(default="Unknown Bank", max_length=255)),
                ("bank_state", models.CharField(default="CA", max_length=2)),
                ("naics_code", models.CharField(default="000000", max_length=6)),
                ("approval_date", models.DateField(blank=True, null=True)),
                ("approval_fy", models.CharField(default="2020", max_length=4)),
                ("term", models.IntegerField(default=120)),
                ("no_of_employees", models.IntegerField(default=1)),
                ("business_type", models.CharField(default="1", max_length=1)),
                ("jobs_created", models.IntegerField(default=0)),
                ("jobs_retained", models.IntegerField(default=0)),
                (
                    "franchise_code",
                    models.CharField(
                        blank=True, default="00000", max_length=6, null=True
                    ),
                ),
                ("urban_rural", models.CharField(default="1", max_length=1)),
                ("revolving_credit", models.CharField(default="N", max_length=1)),
                ("low_doc_program", models.CharField(default="N", max_length=1)),
                ("charge_off_date", models.DateField(blank=True, null=True)),
                ("disbursement_date", models.DateField(blank=True, null=True)),
                (
                    "disbursement_gross",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=15),
                ),
                (
                    "balance_gross",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=15),
                ),
                ("mis_status", models.CharField(default="PIF", max_length=10)),
                (
                    "charge_off_principal",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        default=0.0,
                        max_digits=15,
                        null=True,
                    ),
                ),
                (
                    "gross_approved",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=15),
                ),
                (
                    "sba_approved",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=15),
                ),
            ],
        ),
        migrations.CreateModel(
            name="IndividualBorrower",
            fields=[
                ("member_id", models.AutoField(primary_key=True, serialize=False)),
                ("emp_length", models.IntegerField(blank=True, null=True)),
                (
                    "home_ownership",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("income", models.FloatField()),
                (
                    "verification_status",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("addr_state", models.CharField(blank=True, max_length=10, null=True)),
                (
                    "application_type",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("dti", models.FloatField()),
                ("delinq_2yrs", models.IntegerField(blank=True, null=True)),
                ("inq_last_6mths", models.IntegerField(blank=True, null=True)),
                ("open_acc", models.IntegerField(blank=True, null=True)),
                ("pub_rec", models.IntegerField(blank=True, null=True)),
                ("revol_bal", models.FloatField(blank=True, null=True)),
                ("total_acc", models.IntegerField(blank=True, null=True)),
                (
                    "collections_12_mths_ex_med",
                    models.IntegerField(blank=True, null=True),
                ),
                ("loan_amnt", models.FloatField()),
                ("term", models.CharField(max_length=20)),
                ("int_rate", models.FloatField()),
                ("installment", models.FloatField(blank=True, null=True)),
                ("grade", models.CharField(blank=True, max_length=5, null=True)),
                ("sub_grade", models.CharField(blank=True, max_length=5, null=True)),
                ("purpose", models.CharField(blank=True, max_length=100, null=True)),
                ("default_probability", models.FloatField(default=0.0)),
                ("default_ind", models.BooleanField(default=False)),
                ("last_updated", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
